contact/urls.py
"""
URLConf for Satchmo Contacts.
"""

from django.conf.urls.defaults import *

urlpatterns = patterns('satchmo.contact.views',
    (r'^$', 'view', {}, 'satchmo_account_info'),
    (r'^history/$', 'order_history', {}, 'satchmo_order_history'),
    (r'^tracking/(?P<order_id>\d+)/$', 'order_tracking', {}, 'satchmo_order_tracking'),
    (r'^update/$', 'update', {}, 'satchmo_profile_update'), 
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from satchmo.shop.views.sitemaps import sitemaps

if settings.SHOP_BASE == '':
    shopregex = '^'
else:
    shopregex = '^' + settings.SHOP_BASE[1:] + '/'

urlpatterns = getattr(settings, 'URLS', [])

urlpatterns += patterns('',
    (r'^admin/print/(?P<doc>[-\w]+)/(?P<id>\d+)', 'satchmo.shipping.views.displayDoc'),
    (r'^admin/product/configurableproduct/(?P<id>\d+)/getoptions/', 'satchmo.product.views.getConfigurableProductOptions'),
    (r'^admin/$', 'satchmo.shop.views.admin-portal.home'),
    (r'^print/(?P<doc>[-\w]+)/(?P<id>\d+)', 'satchmo.shipping.views.displayDoc'),
    (r'^admin/', include('django.contrib.admin.urls')),
    (r'^accounts/', include('satchmo.accounts.urls')),
    (shopregex, include('satchmo.shop.urls')),
    (r'sitemap.xml', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^tiny_mce/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/nycavp/webapps/django/satchmo/static/'}),
    (r'^uploads/', include('upload.urls')),
    (r'^search/$', 'satchmo.shop.views.search.search'),
    
)
#For pressroom
urlpatterns += patterns('',
    (r'^pressroom/', include('django_apps.pressroom.urls')),
)
#For photologue
urlpatterns += patterns('',
        (r'^photologue/', include('django_apps.photologue.urls')),
)

#The following is used to serve up local media files like images
if settings.LOCAL_DEV:
    baseurlregex = r'^static/(?P<path>.*)$'
    urlpatterns += patterns('',
        (baseurlregex, 'django.views.static.serve',
        {'document_root':  settings.MEDIA_ROOT}),
    )

def remove_duplicate_urls(urls, names):
    """Remove any URLs whose names are already in use."""
    for pattern in urls:
        if hasattr(pattern, 'url_patterns'):
            remove_duplicate_urls(pattern.url_patterns, names)
        elif hasattr(pattern, 'name') and pattern.name:
            if pattern.name in names:
                urls.remove(pattern)
            else:
                names.append(pattern.name)

remove_duplicate_urls(urlpatterns, [])

product/models.py
"""
Base model used for products.  Stores hierarchical categories
as well as individual product level information which includes
options.
"""

import datetime
import os
from sets import Set
from decimal import Decimal
from django.conf import settings
from django.core import validators, urlresolvers
from django.db import models
from django.utils.translation import ugettext_lazy as _
from satchmo.tax.models import TaxClass
from satchmo.thumbnail.field import ImageWithThumbnailField

if 'IMAGE_DIR' in settings.get_all_members():
    upload_dir = "./" + settings.IMAGE_DIR
else:
    upload_dir = "./images"
    
class Category(models.Model):
    """
    Basic hierarchical category model for storing products
    """
    name = models.CharField(_("Name"), core=True, max_length=200)
    slug = models.SlugField(prepopulate_from=('name',),
        help_text=_("Used for URLs"))
    parent = models.ForeignKey('self', blank=True, null=True,
        related_name='child')
    meta = models.TextField(_("Meta Description"), blank=True, null=True,
        help_text=_("Meta description for this category"))
    description = models.TextField(_("Description"), blank=True,
        help_text="Optional")

    def _recurse_for_parents_slug(self, cat_obj):
        #This is used for the urls
        p_list = []
        if cat_obj.parent_id:
            p = cat_obj.parent
            p_list.append(p.slug)
            more = self._recurse_for_parents_slug(p)
            p_list.extend(more)
        if cat_obj == self and p_list:
            p_list.reverse()
        return p_list

    def get_absolute_url(self):
        p_list = self._recurse_for_parents_slug(self)
        p_list.append(self.slug)
        return u'%s/category/%s/' % (settings.SHOP_BASE, u'/'.join(p_list))

    def _recurse_for_parents_name(self, cat_obj):
        #This is used for the visual display & save validation
        p_list = []
        if cat_obj.parent_id:
            p = cat_obj.parent
            p_list.append(p.name)
            more = self._recurse_for_parents_name(p)
            p_list.extend(more)
        if cat_obj == self and p_list:
            p_list.reverse()
        return p_list

    def get_separator(self):
        return ' :: '

    def _parents_repr(self):
        p_list = self._recurse_for_parents_name(self)
        return self.get_separator().join(p_list)
    _parents_repr.short_description = "Category parents"

    def _recurse_for_parents_name_url(self, cat_obj):
        #Get all the absolute urls and names (for use in site navigation)
        p_list = []
        url_list = []
        if cat_obj.parent_id:
            p = cat_obj.parent
            p_list.append(p.name)
            url_list.append(p.get_absolute_url())
            more, url = self._recurse_for_parents_name_url(p)
            p_list.extend(more)
            url_list.extend(url)
        if cat_obj == self and p_list:
            p_list.reverse()
            url_list.reverse()
        return p_list, url_list

    def get_url_name(self):
        #Get a list of the url to display and the actual urls
        p_list, url_list = self._recurse_for_parents_name_url(self)
        p_list.append(self.name)
        url_list.append(self.get_absolute_url())
        return zip(p_list, url_list)

    def __unicode__(self):
        p_list = self._recurse_for_parents_name(self)
        p_list.append(self.name)
        return self.get_separator().join(p_list)

    def save(self):
        p_list = self._recurse_for_parents_name(self)
        if self.name in p_list:
            raise validators.ValidationError(_("You must not save a category in itself!"))
        super(Category, self).save()

    def _flatten(self, L):
        """
        Taken from a python newsgroup post
        """
        if type(L) != type([]): return [L]
        if L == []: return L
        return self._flatten(L[0]) + self._flatten(L[1:])

    def _recurse_for_children(self, node):
        children = []
        children.append(node)
        for child in node.child.all():
            children_list = self._recurse_for_children(child)
            children.append(children_list)
        return(children)

    def get_all_children(self):
        """
        Gets a list of all of the children categories.
        """
        children_list = self._recurse_for_children(self)
        flat_list = self._flatten(children_list[1:])
        return(flat_list)

    class Admin:
        list_display = ('name', '_parents_repr')
        ordering = ['name']

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

class OptionGroup(models.Model):
    """
    A set of options that can be applied to an item.
    Examples - Size, Color, Shape, etc
    """
    name = models.CharField(_("Name of Option Group"), max_length=50, core=True,
        help_text=_("This will be the text displayed on the product page."))
    description = models.CharField(_("Detailed Description"), max_length=100,
        blank=True,
        help_text=_("Further description of this group (i.e. shirt size vs shoe size)."))
    sort_order = models.IntegerField(_("Sort Order"),
        help_text=_("The order they will be displayed on the screen."))

    def __unicode__(self):
        if self.description:
            return u"%s - %s" % (self.name, self.description)
        else:
            return self.name

    class Admin:
        pass

    class Meta:
        ordering = ['sort_order']
        verbose_name = _("Option Group")
        verbose_name_plural = _("Option Groups")

class OptionManager(models.Manager):
    def from_unique_id(self, str):
        (og, opt) = str.split('-')
        group = OptionGroup.objects.get(id=og)
        return Option.objects.get(optionGroup=og, value=opt)

class Option(models.Model):
    """
    These are the actual items in an OptionGroup.  If the OptionGroup is Size, then an Option
    would be Small.
    """
    objects = OptionManager()
    optionGroup = models.ForeignKey(OptionGroup, edit_inline=models.TABULAR,
        num_in_admin=5)
    name = models.CharField(_("Display value"), max_length=50, core=True)
    value = models.SlugField(_("Stored value"), max_length=50,
        prepopulate_from=('name',))
    price_change = models.DecimalField(_("Price Change"), null=True, blank=True,
        max_digits=10, decimal_places=2,
        help_text=_("This is the price differential for this option."))
    displayOrder = models.IntegerField(_("Display Order"))

    class Meta:
        ordering = ('optionGroup', 'displayOrder')
        unique_together = (('optionGroup', 'value'),)
        verbose_name = _("Option Item")
        verbose_name_plural = _("Option Items")

    def _get_unique_id(self):
        return '%s-%s' % (str(self.optionGroup.id), str(self.value),)
    # optionGroup.id-value
    unique_id = property(_get_unique_id)

    def __repr__(self):
        return u"<Option: %s>" % self.name

    def __unicode__(self):
        return u'%s: %s' % (self.optionGroup.name, self.name)

class ProductManager(models.Manager):
    def active(self):
        return self.filter(active=True)

class Product(models.Model):
    """
    Root class for all Products
    """
    name = models.CharField(_("Full Name"), max_length=255)
    slug = models.SlugField(_("Slug Name"), unique=True, prepopulate_from=('name',), core=True, blank=False)
    short_description = models.TextField(_("Short description of product"), max_length=200, default='', blank=True)
    description = models.TextField(_("Description of product"), help_text=_("This field can contain HTML and should be a few paragraphs explaining the background of the product, and anything that would help the potential customer make their purchase."), default='', blank=True)
    category = models.ManyToManyField(Category, filter_interface=True, blank=True)
    items_in_stock = models.IntegerField(_("Number in stock"), default=0)
    #TODO: Add this, useful for things like DownloadableProducts that wont have stock
    #require_stock = models.BooleanField(default=True)
    meta = models.TextField(_("Meta Description"), max_length=200, blank=True, null=True, help_text=_("Meta description for this product"))
    date_added = models.DateField(null=True, blank=True)
    active = models.BooleanField(_("Is product active?"), default=True, help_text=_("This will determine whether or not this product will appear on the site"))
    featured = models.BooleanField(_("Featured Item"), default=False, help_text=_("Featured items will show on the front page"))
    weight = models.DecimalField(_("Weight"), max_digits=8, decimal_places=2, null=True, blank=True)
    length = models.DecimalField(_("Length"), max_digits=6, decimal_places=2, null=True, blank=True)
    width = models.DecimalField(_("Width"), max_digits=6, decimal_places=2, null=True, blank=True)
    height = models.DecimalField(_("Height"), max_digits=6, decimal_places=2, null=True, blank=True)
    related_items = models.ManyToManyField('self', blank=True, null=True, related_name='related')
    also_purchased = models.ManyToManyField('self', blank=True, null=True, related_name='previouslyPurchased')
    taxable = models.BooleanField(default=False)
    taxClass = models.ForeignKey(TaxClass, blank=True, null=True, help_text=_("If it is taxable, what kind of tax?"))

    objects = ProductManager()

    def _get_mainImage(self):
        img = False
        if self.productimage_set.count() > 0:
            img = self.productimage_set.order_by('sort')[0]
        else:
            # try to get a main image by looking at the parent if this has one
            try:
                parent = self.productvariation.parent
                img = parent.product.main_image
                
            except ProductVariation.DoesNotExist:
                pass
        
        if not img:
            #This should be a "Image Not Found" placeholder image
            try:

contact/views.py
from django import http
from django import newforms as forms
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core import urlresolvers
from django.shortcuts import render_to_response
from django.template import loader, RequestContext, Context
from django.utils.translation import ugettext_lazy as _, ugettext
from forms import ExtendedContactInfoForm
from satchmo.contact.common import get_area_country_options
from satchmo.contact.forms import selection
from satchmo.contact.models import Contact, Order
from satchmo.shop.views.utils import bad_or_missing
import logging

log = logging.getLogger('satchmo.contact.views')

@login_required
def view(request):
    """View contact info."""
    try:
        user_data = Contact.objects.get(user=request.user.id)
    except Contact.DoesNotExist:
        user_data = None
        
    context = RequestContext(request, {'user_data': user_data})
    return render_to_response('contact/view_profile.html', context)

@login_required
def update(request):
    """Update contact info"""

    init_data = {}
    areas, countries, only_country = get_area_country_options(request)

    contact = Contact.from_request(request, create=False)

    if request.POST:
        new_data = request.POST.copy()
        form = ExtendedContactInfoForm(countries, areas, new_data,
            initial=init_data)

        if form.is_valid():
            if contact is None and request.user:
                contact = Contact(user=request.user)
            custID = form.save(contact=contact)
            request.session['custID'] = custID
            url = urlresolvers.reverse('satchmo_account_info')
            return http.HttpResponseRedirect(url)
    else:
        if contact:
            #If a person has their contact info, make sure we populate it in the form
            for item in contact.__dict__.keys():
                init_data[item] = getattr(contact,item)
            if contact.shipping_address:
                for item in contact.shipping_address.__dict__.keys():
                    init_data["ship_"+item] = getattr(contact.shipping_address,item)
            if contact.billing_address:
                for item in contact.billing_address.__dict__.keys():
                    init_data[item] = getattr(contact.billing_address,item)
            if contact.primary_phone:
                init_data['phone'] = contact.primary_phone.phone
        form = ExtendedContactInfoForm(countries, areas, initial=init_data)

    context = RequestContext(request, {
        'form': form,
        'country': only_country})
    return render_to_response('contact/update_form.html', context)
        
@login_required
def order_history(request):
    orders = None
    contact = Contact.from_request(request, create=False)
    if contact:
        try:
            orders = Order.objects.filter(contact=contact).order_by('-timestamp')
        except Order.DoesNotExist:
            pass

    ctx = RequestContext(request, {
        'contact' : contact,
        'orders' : orders})

    return render_to_response('contact/order_history.html', ctx)
    
    
@login_required
def order_tracking(request, order_id):
    order = None
    contact = Contact.from_request(request, create=False)
    if contact:
        try:
            order = Order.objects.get(id__exact=order_id, contact=contact)
        except Order.DoesNotExist:
            pass
    
    if order is None:
        return bad_or_missing(request, _("The order you have requested doesn't exist, or you don't have access to it."))

    ctx = RequestContext(request, {
        'contact' : contact,
        'order' : order})
        
    return render_to_response('contact/order_tracking.html', ctx)

shop/views/search.py
from django.shortcuts import render_to_response
from django.conf import settings
from yahoo.search import web

def search(request):
	query = request.GET.get('q', None)
	site = ['www.avp.org']
	results = None
	if query:
		search = web.WebSearch(settings.YAHOO_ID, query=query, site=site)
		results = search.parse_results()
	return render_to_response('search.html', {'query': query, 'results': results})

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
{% load typogrify.typogrify i18n satchmo.category_display satchmo.google  rendertext %}
{% load tagging_tags %}
{% load several_random %} 
{% load rendertext %}


<head>
<script src="{{media_url}}js/jquery-1.2.1.pack.js"></script> 
<script type="text/javascript" src="{{media_url}}js/jq-corner.js"></script>
<!--script type="text/javascript" src="{{media_url}}js/jquery.corner.pack.js"></script-->
<!--
  jCarousel library
-->
<!--script type="text/javascript" src="{{media_url}}js/jquery.jcarousel.pack.js"></script-->
<!--
  jCarousel core stylesheet
-->
<!--link rel="stylesheet" type="text/css" href="{{media_url}}js/jquery.jcarousel.css" /-->
<!--
  jCarousel skin stylesheet
-->
<!--link rel="stylesheet" type="text/css" href="{{media_url}}js/skins/tango/skin.css" /-->
<script type="text/javascript" src="{{media_url}}js/thickbox-compressed.js"></script>
<link rel="stylesheet" href="{{media_url}}js/thickbox.css" type="text/css" media="screen" />
<link rel="shortcut icon" href="{{media_url}}favicon.ico" />          


<script type="text/javascript" src="{{media_url}}js/jquery.ifixpng.js"></script>   

<script type="text/javascript" src="{{media_url}}js/swfobject.js"></script>






   <link rel="stylesheet" href="{{ media_url }}css/blueprint/screen.css" media="projection,screen"/>
    <link rel="stylesheet" href="{{ media_url }}css/blueprint/print.css" media="print" />
	 	

    <link rel="stylesheet" href="{{ media_url }}css/style.css" /> 
<!--[if IE]><link rel="stylesheet" href="{{ media_url }}css/blueprint/lib/ie.css" type="text/css" media="screen, projection"><![endif]-->
    <title>{{ shop_name}} {% block title %}{% endblock %}</title>
<!-- Show the grid and baseline -->

	<style type="text/css">
		.container {background-image:url({{media_url}}images/inner_bg.png);background-repeat:repeat-x; }
		/*.container {background:url({{media_url}}css/blueprint/lib/grid.png)repeat; }*/
		body{ background-image: url({{media_url}}images/bg.png);background-repeat:no-repeat; 
			  background-position: 0% 0%;
			  }
        .pull-quote{ background-image:url({{media_url}}images/pull_quote.jpg);
                     background-repeat:no-repeat;
                     
                   } 
        #details{background-image: url({{media_url}}images/event_details.gif);background-repeat:no-repeat; 
background-position:0% 100%;} 
        
	</style>
      <script type="text/javascript">
      // <![CDATA[
        $(document).ready(function() {
            var so = new SWFObject("{{media_url}}output.swf", "sotester", "950", "260", "9", "#ffffff");
            so.addParam("wmode", "transparent");
            so.addParam("allowScriptAccess", "always");
            // so.addParam("scale", "noorder");
            so.useExpressInstall('expressinstall.swf');
            so.write("flash_menu");
            //$('.account-info').corner();
            //$('#details').ifixpng();
            //$('div#logo').ifixpng();
            //$('div.side').ifixpng();
            
            if (playerObj = document.getElementById("player")) {
            var so = new SWFObject('{{media_url}}flvplayer.swf','player','707','600','9');
            so.addParam("allowfullscreen","true");
            so.addVariable("file","{{media_url}}playlist.xml");
            so.addVariable("displayheight","480");
            //so.addVariable("logo", "{{media_url}}images/avp_logo_orange.png");
            so.addVariable("backcolor","0xFFFFFF");
            so.addVariable("image", "{{media_url}}images/psa_preview.jpg");
            so.addVariable("screencolor","0xffffff");
            so.write('player');
}
              
            $('#main').corner();
            $('.box1').corner2();
            $('img[@src$=.png]').ifixpng();
{% if user.is_anonymous %}


{%endif%}
            });
    
    
    
            // ]]>
    </script> 
    
    
    
{% block extra-head %}{% endblock %}


    
</head> 
<body>

    <div class="container" id="contain"> 
	<div id="logo" class="column span-24 first last" style="background-image:url({{media_url}}images/logo.gif);background-repeat:no-repeat;padding:0;">
	  <div class="column span-10 prepend-13 append-1 first last " style="margin-bottom:0px;">
          <ul class="account-info push-0" style="margin-bottom:0px;">{% if user.is_authenticated %}
               <li class="first"><a href="{% url satchmo_account_info %}">Account Details</a></li>
              <li><a href="{% url auth_logout %}">Log out</a></li>
            {% else %}
                <li class="first"><a href="{% url auth_login %}">Log in</a></li>
            {% endif %}

            {% load satchmo.currency_filter %}
            <li><a href="{% url satchmo_cart %}">Cart</a>

            {% if cart_count %}
                {{ cart_count}} - {{cart.total|currency }}</li>
                <li><a href="{% url satchmo_checkout-step1 %}">Check out</a></li>
			{% else %}</li>	
            {% endif %}
</ul>
</div>
<div id="details">
<div id="flash_menu" > 
<img src="{{media_url}}images/spacer.gif" width="707px" height="480px" />        
        <center><h3 style="z-index:3">Loading Flash player...</h3></center>
    
</div>
</div>

<hr />
 </div>   
    


    {% block navbar %}
    
    {% endblock %}
  
<div  class="column span-3 first side" {% if form %} {%else%}   style=background-image:url({{media_url}}images/event_photos.png);background-repeat:no-repeat;" {%endif%}>
<hr />
{% if form %} &nbsp; {%else%}  
<div id="mini-gallery" style="padding-left:5px;padding-top:100px;">
{% tags_for_model photologue.Gallery as courage_tag %}
{% tagged_objects courage_tag in photologue.Gallery as galleries %}
{% for gallery in galleries %}
{% for photo in gallery.photos.all|several_random:3 %}

<!--div class="{% cycle gallery-photo-1,gallery-photo-2,gallery-photo-3,gallery-photo-4  %}"-->
            <a href="{{ photo.get_gallery_url }}" title="{% spaceless %}{{photo.caption|truncatewords:15}}{% endspaceless %} - Photo courtesy of {{photo.photographer}}" rel="mini-gallery" class="thickbox"><img src="{{ photo.get_mini_url }}" alt="{{ photo.title }}" style="margin:1px;padding:1px;border:1px solid white;background-color:#cccccc;" /></a>

        <!--/div-->

{% endfor%}

{%endfor%}<center>
<a href="/photologue/gallery/">
{{ "more..."|rendertext:"egypt,18,#FF8F29" }}</a></center>
</div>
<hr />
{% endif %}
{% if user.is_anonymous %}
{% if form %} &nbsp; {%else%}  
<div class="box box1 span-3 news-box" style="margin-left:5px;background-color:#F7981F;padding:0px;" >
{# {{ "Newsletter"|rendertext:"egypt,15,#000000" }} #}
<img src="{{media_url}}images/newsletter.gif" style"margin:0;padding:0" />
<form method="POST" action="http://www.courage-awards.org/accounts/register/">
<table align="center" width="80%">
<tr><td>&nbsp;</td><td>Email:</td></tr>
<tr><td>&nbsp;</td><td><input type="text" id="news_username" class="vTextField required" name="username" size="13" value=""  maxlength="30" /></td></tr>
<tr><td colspan=2 ><button type="submit" class="button clear" ><img src="{{media_url}}css/blueprint/plugins/buttons/icons/tick.png" alt=""/>&nbsp;</button></td></tr>

</table>
</form>

</div> 
{%endif%}
{%endif%}
</div>

  <div class="column span-20 append-1 last"> 
  	<div id="main"{%if latest%}style="background-color:#000000"{%endif%}>
	<!--0p class="push-0"><a href="/pressroom/section/news">News</a> | <a href="/pressroom/section/sponsors">Our Sponsors</a> | <a href="/shop">Purchase Tickets</a> | <a href="/photologue/gallery">Photo Galleries</a></p-->
	
        {# trans "Search" #}
        <!--form id="search" action="{% url satchmo_search %}" method="get">
            <input type="text" size="20" name="keywords" id="search_keywords" /><br/>
            <input type="submit" value="{% trans "Search" %}" />
         </form-->
            {% block sidebar %}
            
                
            
            {% endblock %}

         
            {% block content %}{% endblock %}
    <hr class="space" />    

</div>
 
</div>

        <div id="footer" class="column span-21 prepend-3 quiet first last" >
           <p class="last"> {% blocktrans %} <a href="http://www.courage-awards.org">About</a> | <a href="/privacy">Privacy Policy</a> |{% endblocktrans %} <a href="{% url satchmo_contact %}">{% trans "Contact Us" %}</a><br /> <a href="/shop">Purchase Tickets</a> | <a href="/pressroom/section/sponsors">Our Sponsors</a> | <a href="/pressroom/section/news">News</a> | <a href="/pressroom/section/award-recipients">Award Recipients</a> | <a href="/photologue/gallery">Photologue</a></p>
        </div>


   
    {% block google-tracker %}
    {% if enable_google %}
        {% show_tracker is_secure %}
    {% endif %}
    {% endblock %}
		<hr class="space" />		

 </div>

</body>
</html>

 

templates/base_category.html
{% extends "base.html" %}
{% load i18n %}
{% load satchmo.thumbnail %}
{% load rendertext %}
{% block extra-head %}
<script type="text/javascript" src="http://punc.tilio.us/javascripts/reflection.js"></script>
{% if category.meta %}
    <meta name="description" content="{{ category.meta|escape }}">
{% endif %}
{% endblock %}

{% block navbar %}
{% endblock %}


{% block content %}
<div class="column span-1 first">
<hr style="color:transparent;background:transparent;"/>
</div>
<div id="section" class="column span-18">



<a href="{{ category.get_absolute_url }}">{{ category.name|rendertext:"egypt,30,#cccccc" }}</a>


</div><div class="column span-1 last">
<hr style="color:transparent;background:transparent;"/>
</div>
<div class="column span-4 prepend-1 append-1 first">


<hr style="color:transparent;background:transparent" />
</div>


                <div class="column span-14 last">

<div id="product_category">   
 <ul>
    {% for product in category.product_set.active %} 
            <li><center><a href="{{ product.get_absolute_url }}">
            <img src="{{ product.main_image.get_picture_url|thumbnail:"width=85" }}" width="85" onLoad="Reflection.add(this, { height: 1/5, opacity: 2/5 });" /> </a>
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a></center></li>
    {% endfor %}
    </ul>
{% if child_categories %}
        {% for cat in child_categories %}
            <h4>{{cat.name}}</h4>
            <ul>
            {% for product in cat.product_set.active %}
                <li><center><a href="{{ product.get_absolute_url }}">
                <img src="{{ product.main_image.get_picture_url|thumbnail:"width=85" }}" width="85" onLoad="Reflection.add(this, { height: 1/5, opacity: 2/5 });" /> </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a></center></li>
            {% endfor %}
            </ul>
        {% endfor %}
{% endif %}
</div>
</div>
{% endblock %}

templates/contact_form.html
{% extends "base.html" %}
{% load i18n %}
{% load rendertext %}
{% load typogrify %}
{%block extra-head %}
<script type="text/javascript">
        $(document).ready(function() {
            $(".box1").corner();


        });
    </script>
{%endblock %}
{% block navbar %}
{% endblock %}

{% block content %}
<div class="column span-1 first">
<hr class="space" />
</div>
<div id="section" class="column span-18">
{{ "Contact Us"|rendertext:"egypt,30,#D2D1AD" }}
</div>
<div class="column span-1 last">
<hr class="space" />
</div>
<div class="column span-4  prepend-1 first">
<hr class="space" />
<hr class="space" />
<hr class="space" />
<div class="box box1 span-5">
{{ "For more information about AVP or the 11th Annual Courage Awards, please contact us using the form to the right.  We'll do our best to reply as quickly as possible."|typogrify}} 
<p>
{{ "For more immediate assistance, please contact the Anti-Violence Project's Benefit office:"|typogrify}}<br /> <b>Alyssa Schneiderman</b><br/><b>(212)763-8597</b>
</div>
<div class="column span-2 prepend-1 append-1 first last">
<hr class="space" />
</div>

</div>
<div class="column span-13 prepend-1 append-1 last">
{{ "What's on your mind?"|rendertext:"egypt,45,#D2D1AD" }}
<div class="column span-14  first last">

{% if form.errors %}
<h3>{% blocktrans count form.errors|length as count %}Please correct the following error:{% plural %}Please correct the following errors:{% endblocktrans %}</h3>
{% endif %}

<table>
<form method="post" action=".">
    {{ form.as_table }}
<tr><td></td><td><input type="submit" value="{% trans "Send Email" %}"/></td></tr>
</form>
</table>
</div>
</div>

{% endblock %}

templates/json.html
{{ json }}