urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from satchmo.shop.views.sitemaps import sitemaps

if settings.SHOP_BASE == '':
    shopregex = '^'
else:
    shopregex = '^' + settings.SHOP_BASE[1:] + '/'

urlpatterns = getattr(settings, 'URLS', [])

urlpatterns += patterns('',
    (r'^admin/print/(?P<doc>[-\w]+)/(?P<id>\d+)', 'satchmo.shipping.views.displayDoc'),
    (r'^admin/product/configurableproduct/(?P<id>\d+)/getoptions/', 'satchmo.product.views.getConfigurableProductOptions'),
    (r'^admin/$', 'satchmo.shop.views.admin-portal.home'),
    (r'^print/(?P<doc>[-\w]+)/(?P<id>\d+)', 'satchmo.shipping.views.displayDoc'),
    (r'^admin/', include('django.contrib.admin.urls')),
    (r'^accounts/', include('satchmo.accounts.urls')),
    (shopregex, include('satchmo.shop.urls')),
    (r'sitemap.xml', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^tiny_mce/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/nycavp/webapps/django/satchmo/static/'}),
    (r'^uploads/', include('upload.urls')),
    (r'^search/$', 'satchmo.shop.views.search.search'),
    
)
#For pressroom
urlpatterns += patterns('',
    (r'^pressroom/', include('django_apps.pressroom.urls')),
)
#For photologue
urlpatterns += patterns('',
        (r'^photologue/', include('django_apps.photologue.urls')),
)

#The following is used to serve up local media files like images
if settings.LOCAL_DEV:
    baseurlregex = r'^static/(?P<path>.*)$'
    urlpatterns += patterns('',
        (baseurlregex, 'django.views.static.serve',
        {'document_root':  settings.MEDIA_ROOT}),
    )

def remove_duplicate_urls(urls, names):
    """Remove any URLs whose names are already in use."""
    for pattern in urls:
        if hasattr(pattern, 'url_patterns'):
            remove_duplicate_urls(pattern.url_patterns, names)
        elif hasattr(pattern, 'name') and pattern.name:
            if pattern.name in names:
                urls.remove(pattern)
            else:
                names.append(pattern.name)

remove_duplicate_urls(urlpatterns, [])

i18n/models.py
# -*- coding: utf-8 -*-
# Copyright (c) 2006,  Webda Project
# Licensed under New BSD. Read the file 'LICENSE_BSD'.

from django.db import models
from django.utils.translation import ugettext_lazy as _

CONTINENT = (
    ('af', _('Africa')),
    ('am', _('America')),
    ('e',  _('Europe')),
    ('as', _('Asia')),
    ('o',  _('Oceania')),
)

REGION = (
    ('af.e',  _('Eastern Africa')),
    ('af.m',  _('Middle Africa')),
    ('af.n',  _('Northern Africa')),
    ('af.s',  _('Southern Africa')),
    ('af.w',  _('Western Africa')),
    ('am.ca', _('Caribbean')),
    ('am.c',  _('Central America')),
    ('am.s',  _('South America')),
    ('am.n',  _('Northern America')),
    ('as.c',  _('Central Asia')),
    ('as.e',  _('Eastern Asia')),
    ('as.s',  _('Southern Asia')),
    ('as.se', _('South-Eastern Asia')),
    ('as.w',  _('Western Asia')),
    ('e.e',   _('Eastern Europe')),
    ('e.n',   _('Northern Europe')),
    ('e.s',   _('Southern Europe')),
    ('e.w',   _('Western Europe')),
    ('o.a',   _('Australia and New Zealand')),
    ('o.me',  _('Melanesia')),
    ('o.mi',  _('Micronesia')),
    ('o.p',   _('Polynesia')),
)

AREA = (
    ('a', _('Another')),
    ('i', _('Island')),
    ('ar', _('Arrondissement')),
    ('at', _('Atoll')),
    ('ai', _('Autonomous island')),
    ('ca', _('Canton')),
    ('cm', _('Commune')),
    ('co', _('County')),
    ('dp', _('Department')),
    ('de', _('Dependency')),
    ('dt', _('District')),
    ('dv', _('Division')),
    ('em', _('Emirate')),
    ('gv', _('Governorate')),
    ('ic', _('Island council')),
    ('ig', _('Island group')),
    ('ir', _('Island region')),
    ('kd', _('Kingdom')),
    ('mu', _('Municipality')),
    ('pa', _('Parish')),
    ('pf', _('Prefecture')),
    ('pr', _('Province')),
    ('rg', _('Region')),
    ('rp', _('Republic')),
    ('sh', _('Sheading')),
    ('st', _('State')),
    ('sd', _('Subdivision')),
    ('sj', _('Subject')),
    ('ty', _('Territory')),
)

LANGUAGE_TYPES = (
    ('o', _('official')),
    ('n', _('national')),
    ('r', _('regional')),
    ('f', _('de facto')),
    ('j', _('de jure')),
    ('l', _('legislative')),
    ('b', _('business')),
)


class Language(models.Model):
    """Languages more common.

'synonym' field is used for some languages that are called with
another name too.
    """
    name = models.CharField(_('language name'), max_length=36,
        unique=True)
    iso3_code = models.CharField(_('alpha-3 ISO code'), max_length=3,
        primary_key=True)
    iso2_code = models.CharField(_('alpha-2 ISO code'), max_length=2)
    synonym = models.CharField(_('language synonym'), max_length=32)
    display = models.BooleanField (_('display'), default=False,
        help_text=_('Designates whether the language is shown.'))

    class Meta:
        verbose_name = _('language')
        verbose_name_plural = _('languages')
        ordering = ['name']

    class Admin:
        list_display = ('name', 'iso3_code', 'iso2_code', 'synonym',
                        'display')
        list_filter = ('display',)
        search_fields = ('name', 'synonym', 'iso3_code', 'iso2_code')

    def __unicode__(self):
        return self.iso3_code


class Country(models.Model):
    """Country or territory.

iso2_code and iso3_code are ISO 3166-1 codes.
    """
    name = models.CharField(_('country name'), max_length=48,
        unique=True)
    iso3_code = models.CharField(_('alpha-3 ISO code'), max_length=3,
        primary_key=True)
    iso2_code = models.CharField(_('alpha-2 ISO code'), max_length=2,
        unique=True)
    region = models.CharField(_('geographical region'), max_length=5,
        choices=REGION)
    territory_of = models.CharField(_('territory of'), max_length=3)
    adm_area = models.CharField(_('administrative area'), max_length=2,
        choices=AREA)
    display = models.BooleanField(_('display'), default=True,
        help_text=_('Designates whether the country is shown.'))

    class Meta:
        verbose_name = _('country')
        verbose_name_plural = _('countries')
        ordering = ['name']

    class Admin:
        """
        fields = (
            (_('Sorry! Not allowed to add or modify items in this model.'), {
                'fields': ('iso3_code',)
            }),
        )
        """
        list_display = ('name', 'iso3_code', 'iso2_code', 'territory_of',
                        'adm_area', 'display')
        list_filter = ('region', 'territory_of', 'display')
        search_fields = ('name', 'iso3_code', 'iso2_code')

    def __unicode__(self):
        return self.iso3_code

    def _get_name(self):
        return "%s (%s)" % (self.name, self.iso3_code)
    country_id = property(_get_name)


class CountryLanguage(models.Model):
    """Countries with its languages.
    """
    country = models.ForeignKey(Country, edit_inline=models.TABULAR)
    language = models.ForeignKey(Language, core=True)
    lang_type = models.CharField(_('language type'), max_length=1,
        choices=LANGUAGE_TYPES)
    identifier = models.CharField(_('identifier'), max_length=6,
        primary_key=True)

    class Meta:
        verbose_name = _('country & language')
        verbose_name_plural = _('countries & languages')
        ordering = ['country']
    class Admin:
        list_display = ('country', 'language', 'lang_type')
        list_filter = ('lang_type',)
        search_fields = ('country', 'language')

    def __unicode__(self):
        return u"%s - %s" % (self.country, self.language)


class Area(models.Model):
    """Top-level area division in the country, such as
state, district, province, island, region, etc.

In some countries is necessary for the mail address.
In others it is omitted, and in others it is either optional,
or needed in some cases but omitted in others.
    """
    country = models.ForeignKey(Country, edit_inline=models.TABULAR)
    name_id = models.CharField(_('name identifier'), max_length=6,
        primary_key=True)
    name = models.CharField(_('area name'), max_length=40, core=True)
    alt_name = models.CharField(_('area alternate name'), max_length=32)
    abbrev = models.CharField(_('postal abbreviation'), max_length=3)
    reg_area = models.CharField(_('regional administrative area'), max_length=2,
        choices=AREA)

    class Meta:
        verbose_name = _('area')
        verbose_name_plural = _('areas')
        ordering = ['country']
        unique_together = (('country', 'name'),)
    class Admin:
        list_display = ('country', 'name', 'alt_name', 'abbrev', 'reg_area')
        search_fields = ('name')

    def __unicode__(self):
        if self.abbrev:
            return u'%s (%s)' % (self.abbrev, self.name)
        else:
            return self.name


class TimeZone(models.Model):
    """The time zones for each country or territory.
    """
    country = models.ForeignKey(Country, edit_inline=models.TABULAR)
    tz = models.CharField(_('time zone'), max_length=32, core=True)
    comment = models.CharField(_('comment'), max_length=88)

    class Meta:
        verbose_name = _('time zone')
        verbose_name_plural = _('time zones')
        ordering = ['country']

    class Admin:
        list_display = ('country', 'tz', 'comment')
        search_fields = ('country')

    def __unicode__(self):
        return self.tz


class Phone(models.Model):
    """Information related to phones as country code, lengths, and prefixes.
    """
    country = models.ForeignKey(Country, edit_inline=models.TABULAR)
    code = models.PositiveSmallIntegerField(_('country code'), null=True)
    ln_area = models.CharField(_('length of area code'), max_length=10, core=True)
    ln_sn = models.CharField(_('length of subscriber number (SN)'),
        max_length=8)
    ln_area_sn = models.CharField(_('length of area code and SN'),
        max_length=8)
    nat_prefix = models.CharField(_('national prefix'), max_length=2)
    int_prefix = models.CharField(_('international prefix'), max_length=4)

    class Meta:
        verbose_name = _('phone')
        verbose_name_plural = _('phones')
        ordering = ['country']
    class Admin:
        list_display = ('country', 'code', 'ln_area', 'ln_sn', 'ln_area_sn',
                        'nat_prefix', 'int_prefix')
        search_fields = ('country', 'code')

    def __unicode__(self):
        return self.code and unicode(self.code) or u''

l10n/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _

CONTINENTS = (
    ('AF', _('Africa')),
    ('NA', _('North America')),
    ('EU',  _('Europe')),
    ('AS', _('Asia')),
    ('OC',  _('Oceania')),
    ('SA', _('South America')),
    ('AN', _('Antarctica'))
)

AREAS = (
    ('a', _('Another')),
    ('i', _('Island')),
    ('ar', _('Arrondissement')),
    ('at', _('Atoll')),
    ('ai', _('Autonomous island')),
    ('ca', _('Canton')),
    ('cm', _('Commune')),
    ('co', _('County')),
    ('dp', _('Department')),
    ('de', _('Dependency')),
    ('dt', _('District')),
    ('dv', _('Division')),
    ('em', _('Emirate')),
    ('gv', _('Governorate')),
    ('ic', _('Island council')),
    ('ig', _('Island group')),
    ('ir', _('Island region')),
    ('kd', _('Kingdom')),
    ('mu', _('Municipality')),
    ('pa', _('Parish')),
    ('pf', _('Prefecture')),
    ('pr', _('Province')),
    ('rg', _('Region')),
    ('rp', _('Republic')),
    ('sh', _('Sheading')),
    ('st', _('State')),
    ('sd', _('Subdivision')),
    ('sj', _('Subject')),
    ('ty', _('Territory')),
)



class Country(models.Model):
    """
    International Organization for Standardization (ISO) 3166-1 Country list
    """
    iso2_code = models.CharField(_('ISO alpha-2'), max_length=2, unique=True)
    name = models.CharField(_('Official name (CAPS)'), max_length=128)
    printable_name = models.CharField(_('Country name'), max_length=128)
    iso3_code = models.CharField(_('ISO alpha-3'), max_length=3, unique=True)
    numcode = models.PositiveSmallIntegerField(_('ISO numeric'), null=True, blank=True)
    active = models.BooleanField(_('Country is active'), default=True)
    continent = models.CharField(_('Continent'), choices=CONTINENTS, max_length=2)
    admin_area = models.CharField(_('Administrative Area'), choices=AREAS, max_length=2, null=True, blank=True)
    
    class Meta:
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')
        ordering = ('name',)
        
    class Admin:
        list_display = ('printable_name', 'iso2_code',)
        list_filter = ('continent', 'active')
        search_fields = ('name', 'iso2_code', 'iso3_code')
        
        
    def __unicode__(self):
        return self.printable_name


class AdminArea(models.Model):
    """
    Administrative Area level 1 for a country.  For the US, this would be the states
    """
    country = models.ForeignKey(Country, edit_inline=models.TABULAR)
    name = models.CharField(_('Admin Area name'), max_length=60, core=True)
    abbrev = models.CharField(_('Postal Abbreviation'), max_length=3, null=True, blank=True)
    active = models.BooleanField(_('Area is active'), default=True)

    class Meta:
        verbose_name = _('Administrative Area')
        verbose_name_plural = _('Administrative Areas')
        ordering = ('name',)

    def __unicode__(self):
        return self.name

payment/models.py
"""
Stores details about the available payment options.
Also stores credit card info in an encrypted format.
"""

import base64
from Crypto.Cipher import Blowfish
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from satchmo.payment.paymentsettings import PaymentSettings
from satchmo.contact.models import Order

CREDITCHOICES = PaymentSettings().all('CREDITCHOICES')
PAYMENTCHOICES = PaymentSettings().as_selectpairs()

class PaymentOption(models.Model):
    """
    If there are multiple options - CC, Cash, COD, etc this class allows
    configuration.
    """
    description = models.CharField(_("Description"), max_length=20)
    active = models.BooleanField(_("Active"), 
        help_text=_("Should this be displayed as an option for the user?"))
    optionName = models.CharField(_("Option Name"), max_length=20, 
        choices = PAYMENTCHOICES, unique=True, 
        help_text=_("The class name as defined in payment.py"))
    sortOrder = models.IntegerField(_("Sort Order"))
    
    class Admin:
        list_display = ['optionName','description','active']
        ordering = ['sortOrder']
    
    class Meta:
        verbose_name = "Payment Option"
        verbose_name_plural = "Payment Options"

class CreditCardDetail(models.Model):
    """
    Stores an encrypted CC number, its information, and its
    displayable number.
    """
    order = models.ForeignKey(Order, unique=True, edit_inline=True,
        num_in_admin=1, max_num_in_admin=1)
    creditType = models.CharField(_("Credit Card Type"), max_length=16,
        choices=CREDITCHOICES)
    displayCC = models.CharField(_("CC Number (Last 4 digits)"),
        max_length=4, core=True)
    encryptedCC = models.CharField(_("Encrypted Credit Card"),
        max_length=40, blank=True, null=True, editable=False)
    expireMonth = models.IntegerField(_("Expiration Month"))
    expireYear = models.IntegerField(_("Expiration Year"))
    ccv = models.IntegerField(_("CCV"), blank=True, null=True)
    
    def storeCC(self, ccnum):
        # Take as input a valid cc, encrypt it and store the last 4 digits in a visible form
        # Must remember to save it after calling!
        secret_key = settings.SECRET_KEY
        encryption_object = Blowfish.new(secret_key)
        # block cipher length must be a multiple of 8
        padding = ''
        if (len(ccnum) % 8) <> 0:
            padding = 'X' * (8 - (len(ccnum) % 8))
        self.encryptedCC = base64.b64encode(encryption_object.encrypt(ccnum + padding))
        self.displayCC = ccnum[-4:]
    
    def _decryptCC(self):
        secret_key = settings.SECRET_KEY
        encryption_object = Blowfish.new(secret_key)
        # strip padding from decrypted credit card number
        ccnum = encryption_object.decrypt(base64.b64decode(self.encryptedCC)).rstrip('X')
        return (ccnum)
    decryptedCC = property(_decryptCC) 

    def _expireDate(self):
        return(str(self.expireMonth) + "/" + str(self.expireYear))
    expirationDate = property(_expireDate)
    
    class Meta:
        verbose_name = _("Credit Card")
        verbose_name_plural = _("Credit Cards")

payment/common/views/checkout.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext as _
from satchmo.shop.views.utils import bad_or_missing
from satchmo.contact.models import Order

def success(request):
    """
    The order has been succesfully processed.  This can be used to generate a receipt or some other confirmation
    """
    try:
        order = Order.objects.get(id=request.session['orderID'])
    except KeyError:
        return bad_or_missing(request, _('Your order has already been processed.'))
    del request.session['orderID']
    context = RequestContext(request, {'order': order})
    return render_to_response('checkout/success.html', context)

templates/checkout/form.html
{% extends "base.html" %}
{% load i18n %}
{% load rendertext %}
{% load typogrify %}
{% block extra-head %}   
    <script type="text/javascript">
        $(document).ready(function() {
            $("#checkoutprogress").corner();


        });
    </script>
    {% endblock %}
{% block navbar %}

{% endblock %}

{% block content %}
<div class="column span-1 first">
<hr class="space" />
</div>
<div id="section" class="column span-18">
<img src="{{media_url}}images/checkout.gif" />
</div>
<div class="column span-1 last">
<hr class="space" />
</div>
<div class="column span-1 first">
<hr class="space" />
</div>

<div class="column span-18 first last">
<hr class="space" />
<div id="checkoutprogress">
<ul>
    <li class="first">{% trans "Ship/Bill" %}</li>
    <li >{% trans "Payment" %}</li>
    <li>{% trans "Confirmation" %}</li>
</ul>
</div>
</div>
<div class="column span-1 last">
<hr class="space" />
</div>
<div class="column span-4 prepend-1 first" >
<h3 class="article-description">{{ "Please complete the following information to submit your order."|typogrify}}</h3>

<hr class="space"/>

<p class="quiet">{% trans "You must complete the fields marked with an *." %}</p>
</div>
<div class="column span-10 prepend-2 append-3 last ">

{% if form.non_field_errors %}
<h2>{% trans "Please correct the following error:" %}</h2>
{{ form.non_field_errors }}
{% endif %}
{% if user.is_anonymous %}
<form method="post" action="http://www.courage-awards.org/accounts/login/" >
<input type="hidden" name="next" value="{% url satchmo_checkout-step1 %}" />
<table>
		<tr>
			<td colspan="2">
				{% trans "If you already have an account, you can login now to fill in most of the information below." %}
				{% trans "This is just a convenience, no account is required!" %}
			</td>
		</tr>
		<tr><td><label for="id_username">{% trans "Email Address" %}:</label></td><td><input type="text" id="id_username" class="vTextField required" name="username" size="15" value="" maxlength="30" /></td></tr>
		<tr><td><label for="id_password">{% trans "Password" %}:</label></td><td><input type="password" id="id_password" class="vPasswordField required" name="password" size="15" value="" maxlength="30" /></td></tr>
		<tr><td>&nbsp;</td><td><input type="submit" value="{% trans "Login" %}" /></td></tr>
</table>
</form>
{% endif %}

<form method="post" action="{% url satchmo_checkout-step1 %}">
<table>
   

	<tr><td colspan="2">
		{% ifequal paymentmethod_ct 1 %}{# If we only have one payment method, then the form renders it as a hidden field #}{{ form.paymentmethod }}
		{% else %}<h4>{% trans "How do you want to pay?" %}</h4></td></tr>
	<tr><td><label for="id_paymentmethod">{% trans "Payment method" %}*</label></td> <td>{{ form.paymentmethod }}</td></tr>
    {% if form.paymentmethod.errors %}<tr><td>&nbsp;</td><td>*** {{ form.paymentmethod.errors|join:", " }}</td></tr>{% endif %}

	<tr><td colspan="2">{% endifequal %}<h4>{% trans "Basic Information" %}</h4></td></tr>
    <tr><td><label for="id_email">{% trans "Email address" %}*</label></td> <td>{{ form.email }}</td></tr>
    {% if form.email.errors %}<tr><td>&nbsp;</td><td>*** {{ form.email.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_first_name">{% trans "First name" %}*</label></td><td> {{ form.first_name }}</td></tr>
   {% if form.first_name.errors %}<tr><td>&nbsp;</td><td>*** {{ form.first_name.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_last_name">{% trans "Last name" %}*</label></td><td> {{ form.last_name }}</td></tr>
    {% if form.last_name.errors %}<tr><td>&nbsp;</td><td>*** {{ form.last_name.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_phone">{% trans "Phone number" %}*</label></td><td> {{ form.phone }}</td></tr>
    {% if form.phone.errors %}<tr><td>&nbsp;</td><td>*** {{ form.phone.errors|join:", " }}</td></tr>{% endif %}

    <tr><td colspan="2"><h4>{% trans "Billing Information" %}</h4></td></tr>

    <tr><td><label for="id_street1">{% trans "Street" %}*</label></td><td> {{ form.street1 }}</td></tr>
    {% if form.street1.errors %}<tr><td>&nbsp;</td><td>*** {{ form.street1.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_street2">{% trans "Street" %}</label></td><td> {{ form.street2 }}</td></tr>
    {% if form.street2.errors %}<tr><td>&nbsp;</td><td>*** {{ form.street2.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_city">{% trans "City" %}*</label></td><td> {{ form.city }}</td></tr>
    {% if form.city.errors %}<tr><td>&nbsp;</td><td>*** {{ form.city.errors|join:", " }}</td></tr>{% endif %}

    {% if country %}
      {% if form.fields.state.choices %}
        <tr><td><label for="id_state">{{ country.get_admin_area_display }}*</label></td><td> {{ form.state }}</td></tr>
      {% endif %}
    {% else %}
      <tr><td><label for="id_state">{% trans "State/Province" %}</label></td><td> {{ form.state }}</td></tr>
    {% endif %}
    {% if form.state.errors %}<tr><td>&nbsp;</td><td>*** {{ form.state.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_postal_code">{% trans "Zipcode/Postcode" %}*</label></td><td> {{ form.postal_code }}</td></tr>
    {% if form.postal_code.errors %}<tr><td>&nbsp;</td><td>*** {{ form.postal_code.errors|join:", " }}</td></tr>{% endif %}

    {% if not country %}
    <tr><td><label for="id_country">{% trans "Country" %}</label></td><td> {{ form.country }}</td></tr>
    {% if form.country.errors %}<tr><td>&nbsp;</td><td>*** {{ form.country.errors|join:", " }}</td></tr>{% endif %}
    {% endif %}

{% if cart.is_shippable %}
    <tr><td colspan="2"><h4>{% trans "Shipping Information" %}</h4></td></tr>

    <tr><td><label for="id_copy_address">{% trans "Shipping same as billing?" %}</label></td><td> {{ form.copy_address }}</td></tr>
    {% if form.copy_address.errors %}<tr><td>&nbsp;</td><td>*** {{ form.copy_address.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_ship_street1">{% trans "Street" %}</label></td><td> {{ form.ship_street1 }}</td></tr>
    {% if form.ship_street1.errors %}<tr><td>&nbsp;</td><td>*** {{ form.ship_street1.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_ship_street2">{% trans "Street" %}</label></td><td> {{ form.ship_street2 }}</td></tr>
    {% if form.ship_street2.errors %}<tr><td>&nbsp;</td><td>*** {{ form.ship_street2.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_ship_city">{% trans "City" %}</label></td><td> {{ form.ship_city }}</td></tr>
    {% if form.ship_city.errors %}<tr><td>&nbsp;</td><td>*** {{ form.ship_city.errors|join:", " }}</td></tr>{% endif %}

    {% if country %}
      {% if form.fields.ship_state.choices %}
        <tr><td><label for="id_ship_state">{{ country.get_admin_area_display }}*</label></td><td> {{ form.ship_state }}</td></tr>
      {% endif %}
    {% else %}
      <tr><td><label for="id_ship_state">{% trans "State/Province" %}</label></td><td> {{ form.ship_state }}</td></tr>
    {% endif %}
    {% if form.ship_state.errors %}<tr><td>&nbsp;</td><td>*** {{ form.ship_state.errors|join:", " }}</td></tr>{% endif %}

    <tr><td><label for="id_ship_postal_code">{% trans "Zipcode/Postcode" %}</label></td><td>{{ form.ship_postal_code }}</td></tr>
    {% if form.ship_postal_code.errors %}<tr><td>&nbsp;</td><td>*** {{ form.ship_postal_code.errors|join:", " }}</td></tr>{% endif %}
{% endif %}

	<tr><td></td><td><input type="submit" value="{% trans "Continue Checkout" %}"/></td></tr>
</table>
</form>

</div>
{% endblock %}

templates/checkout/pay_ship.html
{% extends "checkout/base_pay_ship.html" %}
{% load i18n %}
{# credit card pay_ship version - we just need to collect CC info #}

{% block payment_table %}
    <tr><td><h4>{% trans "Payment Information" %}</h4></td></tr>
    {% if not PAYMENT_LIVE %}
    <tr><td valign="top"><b>TEST MODE</b></td><td><i>Use Visa 4111111111111111 for CC#<br/>any future date for expiration<br/>any 3 digit CCV</i></td></tr>
    {% endif %}

    <tr><td><label for="id_credit_type">{% trans "Type of credit card" %}</label></td> <td>{{ form.credit_type }}</td></tr>
    <tr><td></td><td>{% if form.credit_type.errors %}<span class="error">*** {{ form.credit_type.errors|join:", " }}</span>{% endif %}</td></tr>

    <tr><td><label for="id_credit_number">{% trans "Credit card number" %}</label></td><td> {{ form.credit_number }}</td></tr>
    <tr><td></td><td>{% if form.credit_number.errors %}<span class="error">*** {{ form.credit_number.errors|join:", " }}</span>{% endif %}</td></tr>

    <tr><td><label for="id_month_expires">{% trans "Expiration date" %}</label><label for+"id_year_expires"></label></td><td> {{ form.month_expires }} {{form.year_expires}}</td></tr>
    <tr><td></td><td>{% if form.year_expires.errors %}<span class="error">*** {{ form.year_expires.errors|join:", " }}</span>{% endif %}</td></tr>

    <tr><td><label for="id_ccv">{% trans "CCV" %}</label></td><td> {{ form.ccv}}</td></tr>
    <tr><td></td><td>{% if form.ccv.errors %}<span class="error">*** {{ form.ccv.errors|join:", " }}</span>{% endif %}</td></tr>

{% endblock %}