urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from satchmo.shop.views.sitemaps import sitemaps

if settings.SHOP_BASE == '':
    shopregex = '^'
else:
    shopregex = '^' + settings.SHOP_BASE[1:] + '/'

urlpatterns = getattr(settings, 'URLS', [])

urlpatterns += patterns('',
    (r'^admin/print/(?P<doc>[-\w]+)/(?P<id>\d+)', 'satchmo.shipping.views.displayDoc'),
    (r'^admin/product/configurableproduct/(?P<id>\d+)/getoptions/', 'satchmo.product.views.getConfigurableProductOptions'),
    (r'^admin/$', 'satchmo.shop.views.admin-portal.home'),
    (r'^print/(?P<doc>[-\w]+)/(?P<id>\d+)', 'satchmo.shipping.views.displayDoc'),
    (r'^admin/', include('django.contrib.admin.urls')),
    (r'^accounts/', include('satchmo.accounts.urls')),
    (shopregex, include('satchmo.shop.urls')),
    (r'sitemap.xml', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    (r'^tiny_mce/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/nycavp/webapps/django/satchmo/static/'}),
    (r'^uploads/', include('upload.urls')),
    (r'^search/$', 'satchmo.shop.views.search.search'),
    
)
#For pressroom
urlpatterns += patterns('',
    (r'^pressroom/', include('django_apps.pressroom.urls')),
)
#For photologue
urlpatterns += patterns('',
        (r'^photologue/', include('django_apps.photologue.urls')),
)

#The following is used to serve up local media files like images
if settings.LOCAL_DEV:
    baseurlregex = r'^static/(?P<path>.*)$'
    urlpatterns += patterns('',
        (baseurlregex, 'django.views.static.serve',
        {'document_root':  settings.MEDIA_ROOT}),
    )

def remove_duplicate_urls(urls, names):
    """Remove any URLs whose names are already in use."""
    for pattern in urls:
        if hasattr(pattern, 'url_patterns'):
            remove_duplicate_urls(pattern.url_patterns, names)
        elif hasattr(pattern, 'name') and pattern.name:
            if pattern.name in names:
                urls.remove(pattern)
            else:
                names.append(pattern.name)

remove_duplicate_urls(urlpatterns, [])

i18n/models.py
# -*- coding: utf-8 -*-
# Copyright (c) 2006,  Webda Project
# Licensed under New BSD. Read the file 'LICENSE_BSD'.

from django.db import models
from django.utils.translation import ugettext_lazy as _

CONTINENT = (
    ('af', _('Africa')),
    ('am', _('America')),
    ('e',  _('Europe')),
    ('as', _('Asia')),
    ('o',  _('Oceania')),
)

REGION = (
    ('af.e',  _('Eastern Africa')),
    ('af.m',  _('Middle Africa')),
    ('af.n',  _('Northern Africa')),
    ('af.s',  _('Southern Africa')),
    ('af.w',  _('Western Africa')),
    ('am.ca', _('Caribbean')),
    ('am.c',  _('Central America')),
    ('am.s',  _('South America')),
    ('am.n',  _('Northern America')),
    ('as.c',  _('Central Asia')),
    ('as.e',  _('Eastern Asia')),
    ('as.s',  _('Southern Asia')),
    ('as.se', _('South-Eastern Asia')),
    ('as.w',  _('Western Asia')),
    ('e.e',   _('Eastern Europe')),
    ('e.n',   _('Northern Europe')),
    ('e.s',   _('Southern Europe')),
    ('e.w',   _('Western Europe')),
    ('o.a',   _('Australia and New Zealand')),
    ('o.me',  _('Melanesia')),
    ('o.mi',  _('Micronesia')),
    ('o.p',   _('Polynesia')),
)

AREA = (
    ('a', _('Another')),
    ('i', _('Island')),
    ('ar', _('Arrondissement')),
    ('at', _('Atoll')),
    ('ai', _('Autonomous island')),
    ('ca', _('Canton')),
    ('cm', _('Commune')),
    ('co', _('County')),
    ('dp', _('Department')),
    ('de', _('Dependency')),
    ('dt', _('District')),
    ('dv', _('Division')),
    ('em', _('Emirate')),
    ('gv', _('Governorate')),
    ('ic', _('Island council')),
    ('ig', _('Island group')),
    ('ir', _('Island region')),
    ('kd', _('Kingdom')),
    ('mu', _('Municipality')),
    ('pa', _('Parish')),
    ('pf', _('Prefecture')),
    ('pr', _('Province')),
    ('rg', _('Region')),
    ('rp', _('Republic')),
    ('sh', _('Sheading')),
    ('st', _('State')),
    ('sd', _('Subdivision')),
    ('sj', _('Subject')),
    ('ty', _('Territory')),
)

LANGUAGE_TYPES = (
    ('o', _('official')),
    ('n', _('national')),
    ('r', _('regional')),
    ('f', _('de facto')),
    ('j', _('de jure')),
    ('l', _('legislative')),
    ('b', _('business')),
)


class Language(models.Model):
    """Languages more common.

'synonym' field is used for some languages that are called with
another name too.
    """
    name = models.CharField(_('language name'), max_length=36,
        unique=True)
    iso3_code = models.CharField(_('alpha-3 ISO code'), max_length=3,
        primary_key=True)
    iso2_code = models.CharField(_('alpha-2 ISO code'), max_length=2)
    synonym = models.CharField(_('language synonym'), max_length=32)
    display = models.BooleanField (_('display'), default=False,
        help_text=_('Designates whether the language is shown.'))

    class Meta:
        verbose_name = _('language')
        verbose_name_plural = _('languages')
        ordering = ['name']

    class Admin:
        list_display = ('name', 'iso3_code', 'iso2_code', 'synonym',
                        'display')
        list_filter = ('display',)
        search_fields = ('name', 'synonym', 'iso3_code', 'iso2_code')

    def __unicode__(self):
        return self.iso3_code


class Country(models.Model):
    """Country or territory.

iso2_code and iso3_code are ISO 3166-1 codes.
    """
    name = models.CharField(_('country name'), max_length=48,
        unique=True)
    iso3_code = models.CharField(_('alpha-3 ISO code'), max_length=3,
        primary_key=True)
    iso2_code = models.CharField(_('alpha-2 ISO code'), max_length=2,
        unique=True)
    region = models.CharField(_('geographical region'), max_length=5,
        choices=REGION)
    territory_of = models.CharField(_('territory of'), max_length=3)
    adm_area = models.CharField(_('administrative area'), max_length=2,
        choices=AREA)
    display = models.BooleanField(_('display'), default=True,
        help_text=_('Designates whether the country is shown.'))

    class Meta:
        verbose_name = _('country')
        verbose_name_plural = _('countries')
        ordering = ['name']

    class Admin:
        """
        fields = (
            (_('Sorry! Not allowed to add or modify items in this model.'), {
                'fields': ('iso3_code',)
            }),
        )
        """
        list_display = ('name', 'iso3_code', 'iso2_code', 'territory_of',
                        'adm_area', 'display')
        list_filter = ('region', 'territory_of', 'display')
        search_fields = ('name', 'iso3_code', 'iso2_code')

    def __unicode__(self):
        return self.iso3_code

    def _get_name(self):
        return "%s (%s)" % (self.name, self.iso3_code)
    country_id = property(_get_name)


class CountryLanguage(models.Model):
    """Countries with its languages.
    """
    country = models.ForeignKey(Country, edit_inline=models.TABULAR)
    language = models.ForeignKey(Language, core=True)
    lang_type = models.CharField(_('language type'), max_length=1,
        choices=LANGUAGE_TYPES)
    identifier = models.CharField(_('identifier'), max_length=6,
        primary_key=True)

    class Meta:
        verbose_name = _('country & language')
        verbose_name_plural = _('countries & languages')
        ordering = ['country']
    class Admin:
        list_display = ('country', 'language', 'lang_type')
        list_filter = ('lang_type',)
        search_fields = ('country', 'language')

    def __unicode__(self):
        return u"%s - %s" % (self.country, self.language)


class Area(models.Model):
    """Top-level area division in the country, such as
state, district, province, island, region, etc.

In some countries is necessary for the mail address.
In others it is omitted, and in others it is either optional,
or needed in some cases but omitted in others.
    """
    country = models.ForeignKey(Country, edit_inline=models.TABULAR)
    name_id = models.CharField(_('name identifier'), max_length=6,
        primary_key=True)
    name = models.CharField(_('area name'), max_length=40, core=True)
    alt_name = models.CharField(_('area alternate name'), max_length=32)
    abbrev = models.CharField(_('postal abbreviation'), max_length=3)
    reg_area = models.CharField(_('regional administrative area'), max_length=2,
        choices=AREA)

    class Meta:
        verbose_name = _('area')
        verbose_name_plural = _('areas')
        ordering = ['country']
        unique_together = (('country', 'name'),)
    class Admin:
        list_display = ('country', 'name', 'alt_name', 'abbrev', 'reg_area')
        search_fields = ('name')

    def __unicode__(self):
        if self.abbrev:
            return u'%s (%s)' % (self.abbrev, self.name)
        else:
            return self.name


class TimeZone(models.Model):
    """The time zones for each country or territory.
    """
    country = models.ForeignKey(Country, edit_inline=models.TABULAR)
    tz = models.CharField(_('time zone'), max_length=32, core=True)
    comment = models.CharField(_('comment'), max_length=88)

    class Meta:
        verbose_name = _('time zone')
        verbose_name_plural = _('time zones')
        ordering = ['country']

    class Admin:
        list_display = ('country', 'tz', 'comment')
        search_fields = ('country')

    def __unicode__(self):
        return self.tz


class Phone(models.Model):
    """Information related to phones as country code, lengths, and prefixes.
    """
    country = models.ForeignKey(Country, edit_inline=models.TABULAR)
    code = models.PositiveSmallIntegerField(_('country code'), null=True)
    ln_area = models.CharField(_('length of area code'), max_length=10, core=True)
    ln_sn = models.CharField(_('length of subscriber number (SN)'),
        max_length=8)
    ln_area_sn = models.CharField(_('length of area code and SN'),
        max_length=8)
    nat_prefix = models.CharField(_('national prefix'), max_length=2)
    int_prefix = models.CharField(_('international prefix'), max_length=4)

    class Meta:
        verbose_name = _('phone')
        verbose_name_plural = _('phones')
        ordering = ['country']
    class Admin:
        list_display = ('country', 'code', 'ln_area', 'ln_sn', 'ln_area_sn',
                        'nat_prefix', 'int_prefix')
        search_fields = ('country', 'code')

    def __unicode__(self):
        return self.code and unicode(self.code) or u''

shop/views/comments.py
"""Satchmo product rating views"""
from django.conf import settings
from django.contrib.comments.models import Comment
from django.contrib.comments.views.comments import post_comment
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, Http404
from logging import getLogger

log = getLogger('satchmo.shop.views.ratings')

def post_rating(request, url='/ratings/posted/', maxcomments=1):
    """Wrap django.contrib.comments.views.comments.post_comment, so that we can control where the user
    is returned after submit, also add the ability to control the maximum number of ratings per user 
    per product.
    """
    if request.POST.has_key('url'):
        url = request.POST['url']
        
    response = post_comment(request)

    if maxcomments > 0 and not request.user.is_anonymous():
        try:
            target = request.POST['target']
        except KeyError:
            raise Http404, _("One or more of the required fields wasn't submitted")
            
        content_type_id, object_id = target.split(':')
        
        try:
            ct = ContentType.objects.get(pk=content_type_id)
        except ContentType.DoesNotExist:
            raise Http404, _("Bad ContentType: %s" % content_type_id)
        
        comments = Comment.objects.filter(object_id__exact=object_id,
            content_type__app_label__exact=ct.app_label,
            content_type__model__exact=ct.model,
            site__id__exact=settings.SITE_ID,
            is_public__exact=True,
            user__exact=request.user.id).order_by('submit_date')
            
        ct = len(comments)
        if ct > maxcomments:
            log.debug("Got %i comments for user - removing all but %i", ct, maxcomments)
            for c in comments:
                c.delete()
                ct -= 1
                if ct == maxcomments: break
    
    return HttpResponseRedirect(url)

templates/comments/form.html
{% load i18n %}
{% if display_form %}
<form {% if photos_optional or photos_required %}enctype="multipart/form-data" {% endif %}action="/comments/post/" method="post">

{% comment %}
{% if user.is_authenticated %}
<p>{% trans "Username:" %} <strong>{{ user.username }}</strong></p>
{% else %}
<p><label for="id_username">{% trans "Username:" %}</label> <input type="text" name="username" id="id_username" /><br />{% trans "Password:" %} <input type="password" name="password" id="id_password" /> (<a href="/accounts/password_reset/">{% trans "Forgotten your password?" %}</a>)</p>
{% endif %}
{% endcomment %}

{% if ratings_optional or ratings_required %}
{# <p>{% trans "Ratings" %} ({% if ratings_required %}{% trans "Required" %}{% else %}{% trans "Optional" %}{% endif %}):</p> #}
<table>
<tr><th>&nbsp;</th>{% for value in rating_range %}<th>{{ value }}</th>{% endfor %}</tr>
{% for rating in rating_choices %}
<tr><th>{{ rating }}&nbsp;</th>{% for value in rating_range %}<th><input type="radio" name="rating{{ forloop.parentloop.counter }}" value="{{ value }}" /></th>{% endfor %}</tr>
{% endfor %}
</table>
<input type="hidden" name="rating_options" value="{{ rating_options }}" />
{% endif %}

{% if photos_optional or photos_required %}
<p><label for="id_photo">{% trans "Post a photo" %}</label> ({% if photos_required %}{% trans "Required" %}{% else %}{% trans "Optional" %}{% endif %}):
<input type="file" name="photo" id="id_photo" /></p>
<input type="hidden" name="photo_options" value="{{ photo_options }}" />
{% endif %}

<p><label for="id_comment">{% trans "Review:" %}</label><br />
<textarea name="comment" id="id_comment" rows="5" cols="60"></textarea></p>

<p>
<input type="hidden" name="options" value="{{ options }}" />
<input type="hidden" name="target" value="{{ target }}" />
<input type="hidden" name="gonzo" value="{{ hash }}" />
<input type="hidden" name="url" value="{{ request.get_full_path }}" />
{# <input type="submit" name="preview" value="{% trans "Preview comment" %}" /> #}
<input type="submit" name="post" value="{% trans "Send review" %}" />
</p>
</form>
{% endif %}

templates/comments/posted.html
<h1>Comment posted successfully</h1>

<p>Thanks for contributing.</p>

{% if object %}
	<ul>
		<li><a href="{{ object.get_absolute_url }}">View your comment</a></li>
	</ul>
{% endif %}

templates/comments/preview.html
<h1>Preview your comment</h1>

<form action="../postfree/" method="post">
	{% if comment_form.has_errors %}
	    <p><strong style="color: red;">Please correct the following errors.</strong></p>
	{% else %}
	    <div class="comment">
	    {{ comment.comment|escape|urlizetrunc:"40"|linebreaks }}
	    <p class="date small">Posted by <strong>{{ comment.person_name|escape }}</strong></p>
	    </div>

	    <p><input type="submit" name="post" value="Post public comment" /></p>

	    <h1>Or edit it again</h1>
	{% endif %}

	{% if comment_form.person_name.errors %}
	    {{ comment_form.person_name.html_error_list }}
	{% endif %}

	<p><label for="id_person_name">Your name:</label> {{ comment_form.person_name }}</p>

	{% if comment_form.comment.errors %}
		{{ comment_form.comment.html_error_list }}
	{% endif %}

	<p>
		<label for="id_comment">Comment:</label>
		<br />
		{{ comment_form.comment }}
	</p>
	
	<input type="hidden" name="options" value="{{ options }}" />
	<input type="hidden" name="target" value="{{ target }}" />
	<input type="hidden" name="gonzo" value="{{ hash }}" />

	<p>
		<input type="submit" name="preview" value="Preview revised comment" />
	</p>
</form>